import { ActividadEspecifica } from './actividadEspecifica';
import { Cdp } from './cdp';
import { RubroPresupuestal } from './rubroPresupuestal';

export class DetalleCDP {
  detalleCdpId: number;
  pcpId: number;
  idArchivo: number;
  cdp: number;
  proy: number;
  prod: number;
  proyecto: string;
  actividadBpin: string;
  planDeCompras: string;
  responsable: string;
  dependencia: string;
  dependenciaDescripcion: string;
  valorAct: number;
  saldoAct: number;
  valorModif: number;
  valorCDP: number;
  saldoCDP: number;
  valorRP: number;
  valorOB: number;
  valorOP: number;
  valorTotal: number;
  aplicaContrato: boolean;
  aplicaContratoDescripcion: boolean;
  saldoTotal: number;
  saldoDisponible: number;
  area: string;
  crp: number;
  valorConvenio: number;
  convenio: number;
  decreto: string;
  valorSolicitud: number;
  estadoModificacion: number;
  actividadEspecifica: ActividadEspecifica;
  usuarioId: number;
  dependenciaId: number;
  rubroPresupuestal: RubroPresupuestal;
  cdpDocumento: Cdp;
  clavePresupuestalContableId: number;
  esSeleccionada: boolean;
  identificacionPci: string;
}
