//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 
namespace ComplementApp.API.Dtos.Serializacion.Obligacion {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    [System.Xml.Serialization.XmlRootAttribute("obligacionPptal", Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg", IsNullable=false)]
    public partial class tipoObligacionPptal {
        
        private tipoListaFiltroConsulta listaFiltroConsultaField;
        
        private tipoItemObligacion[] listaItemObligacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoListaFiltroConsulta listaFiltroConsulta {
            get {
                return this.listaFiltroConsultaField;
            }
            set {
                this.listaFiltroConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemObligacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemObligacion[] listaItemObligacion {
            get {
                return this.listaItemObligacionField;
            }
            set {
                this.listaItemObligacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoListaFiltroConsulta {
        
        private string codPCIField;
        
        private string codPCIConsultaField;
        
        private string areaField;
        
        private enumCodTipoVigencia codTipoVigenciaField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private enumSINO deduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCI {
            get {
                return this.codPCIField;
            }
            set {
                this.codPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCIConsulta {
            get {
                return this.codPCIConsultaField;
            }
            set {
                this.codPCIConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumCodTipoVigencia codTipoVigencia {
            get {
                return this.codTipoVigenciaField;
            }
            set {
                this.codTipoVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumSINO deduccion {
            get {
                return this.deduccionField;
            }
            set {
                this.deduccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumCodTipoVigencia {
        
        /// <remarks/>
        ACTUAL,
        
        /// <remarks/>
        RESERVAS_PRESUPUESTALES,
        
        /// <remarks/>
        CUENTAS_POR_PAGAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumSINO {
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        NO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoDatosAdminSimple {
        
        private System.DateTime fechaField;
        
        private string codTipoDocSoporteField;
        
        private string nomTipoDocSoporteField;
        
        private string numDocSoporteField;
        
        private string notasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoDocSoporte {
            get {
                return this.codTipoDocSoporteField;
            }
            set {
                this.codTipoDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTipoDocSoporte {
            get {
                return this.nomTipoDocSoporteField;
            }
            set {
                this.nomTipoDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocSoporte {
            get {
                return this.numDocSoporteField;
            }
            set {
                this.numDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemDeduccion {
        
        private string codPosPagoNoPptalField;
        
        private string nomPosPagoNoPptalField;
        
        private tipoTerceroBasico terceroBeneficiarioField;
        
        private System.Nullable<decimal> baseGravableField;
        
        private string tarifaField;
        
        private decimal valorDeducirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPosPagoNoPptal {
            get {
                return this.codPosPagoNoPptalField;
            }
            set {
                this.codPosPagoNoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPosPagoNoPptal {
            get {
                return this.nomPosPagoNoPptalField;
            }
            set {
                this.nomPosPagoNoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoTerceroBasico terceroBeneficiario {
            get {
                return this.terceroBeneficiarioField;
            }
            set {
                this.terceroBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> baseGravable {
            get {
                return this.baseGravableField;
            }
            set {
                this.baseGravableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorDeducir {
            get {
                return this.valorDeducirField;
            }
            set {
                this.valorDeducirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoTerceroBasico {
        
        private string nomTerceroField;
        
        private string codNaturalezaField;
        
        private string nomNaturalezaField;
        
        private string codTipoDocumentoField;
        
        private string nomTipoDocumentoField;
        
        private string numDocIdentidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTercero {
            get {
                return this.nomTerceroField;
            }
            set {
                this.nomTerceroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codNaturaleza {
            get {
                return this.codNaturalezaField;
            }
            set {
                this.codNaturalezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomNaturaleza {
            get {
                return this.nomNaturalezaField;
            }
            set {
                this.nomNaturalezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoDocumento {
            get {
                return this.codTipoDocumentoField;
            }
            set {
                this.codTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTipoDocumento {
            get {
                return this.nomTipoDocumentoField;
            }
            set {
                this.nomTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocIdentidad {
            get {
                return this.numDocIdentidadField;
            }
            set {
                this.numDocIdentidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemReintegro {
        
        private long codReintegroField;
        
        private decimal valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codReintegro {
            get {
                return this.codReintegroField;
            }
            set {
                this.codReintegroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoDocRelacionObligacion {
        
        private long codSolicitudCDPField;
        
        private long codCDPField;
        
        private long codCompromisoField;
        
        private System.Nullable<long> codCuentaPagarField;
        
        private System.Nullable<System.DateTime> fechaRegCuentaPagarField;
        
        private System.Nullable<long> codOrdenPagoField;
        
        private tipoItemReintegro[] listaItemReintegroField;
        
        private string codCompContableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codSolicitudCDP {
            get {
                return this.codSolicitudCDPField;
            }
            set {
                this.codSolicitudCDPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codCDP {
            get {
                return this.codCDPField;
            }
            set {
                this.codCDPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codCompromiso {
            get {
                return this.codCompromisoField;
            }
            set {
                this.codCompromisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long> codCuentaPagar {
            get {
                return this.codCuentaPagarField;
            }
            set {
                this.codCuentaPagarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> fechaRegCuentaPagar {
            get {
                return this.fechaRegCuentaPagarField;
            }
            set {
                this.fechaRegCuentaPagarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long> codOrdenPago {
            get {
                return this.codOrdenPagoField;
            }
            set {
                this.codOrdenPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemReintegro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemReintegro[] listaItemReintegro {
            get {
                return this.listaItemReintegroField;
            }
            set {
                this.listaItemReintegroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string codCompContable {
            get {
                return this.codCompContableField;
            }
            set {
                this.codCompContableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoUsosPptales {
        
        private string codUsoPptalField;
        
        private string nomUsoPptalField;
        
        private decimal valorUsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codUsoPptal {
            get {
                return this.codUsoPptalField;
            }
            set {
                this.codUsoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomUsoPptal {
            get {
                return this.nomUsoPptalField;
            }
            set {
                this.nomUsoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorUso {
            get {
                return this.valorUsoField;
            }
            set {
                this.valorUsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemAfectacion {
        
        private string codDepAfectacionField;
        
        private string nomDepAfectacionField;
        
        private string codPosicionGastoField;
        
        private string nomPosicionGastoField;
        
        private string codFuenteFinanciacionField;
        
        private enumFuenteFinanciacion nomFuenteFinanciacionField;
        
        private string codRecursoPptalField;
        
        private string nomRecursoPptalField;
        
        private string codSituacionFondosField;
        
        private enumSituacionFondos nomSituacionFondosField;
        
        private decimal valorInicialField;
        
        private decimal valorOperacionesField;
        
        private decimal valorActualField;
        
        private decimal saldoUtilizarField;
        
        private string codAtributoContableField;
        
        private string nomAtributoContableField;
        
        private tipoUsosPptales[] listaUsosPpalesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codDepAfectacion {
            get {
                return this.codDepAfectacionField;
            }
            set {
                this.codDepAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomDepAfectacion {
            get {
                return this.nomDepAfectacionField;
            }
            set {
                this.nomDepAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPosicionGasto {
            get {
                return this.codPosicionGastoField;
            }
            set {
                this.codPosicionGastoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPosicionGasto {
            get {
                return this.nomPosicionGastoField;
            }
            set {
                this.nomPosicionGastoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codFuenteFinanciacion {
            get {
                return this.codFuenteFinanciacionField;
            }
            set {
                this.codFuenteFinanciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumFuenteFinanciacion nomFuenteFinanciacion {
            get {
                return this.nomFuenteFinanciacionField;
            }
            set {
                this.nomFuenteFinanciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codRecursoPptal {
            get {
                return this.codRecursoPptalField;
            }
            set {
                this.codRecursoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomRecursoPptal {
            get {
                return this.nomRecursoPptalField;
            }
            set {
                this.nomRecursoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codSituacionFondos {
            get {
                return this.codSituacionFondosField;
            }
            set {
                this.codSituacionFondosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumSituacionFondos nomSituacionFondos {
            get {
                return this.nomSituacionFondosField;
            }
            set {
                this.nomSituacionFondosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorInicial {
            get {
                return this.valorInicialField;
            }
            set {
                this.valorInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorOperaciones {
            get {
                return this.valorOperacionesField;
            }
            set {
                this.valorOperacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorActual {
            get {
                return this.valorActualField;
            }
            set {
                this.valorActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal saldoUtilizar {
            get {
                return this.saldoUtilizarField;
            }
            set {
                this.saldoUtilizarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codAtributoContable {
            get {
                return this.codAtributoContableField;
            }
            set {
                this.codAtributoContableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomAtributoContable {
            get {
                return this.nomAtributoContableField;
            }
            set {
                this.nomAtributoContableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemUsoPptal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoUsosPptales[] listaUsosPpales {
            get {
                return this.listaUsosPpalesField;
            }
            set {
                this.listaUsosPpalesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumFuenteFinanciacion {
        
        /// <remarks/>
        NACION,
        
        /// <remarks/>
        PROPIOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumSituacionFondos {
        
        /// <remarks/>
        CSF,
        
        /// <remarks/>
        SSF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoCuentaBancaria {
        
        private System.Nullable<enumTipoCuentaBancaria> codTipoCuentaField;
        
        private string numCuentaField;
        
        private string estadoField;
        
        private string nitEntidadField;
        
        private string nombreEntidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<enumTipoCuentaBancaria> codTipoCuenta {
            get {
                return this.codTipoCuentaField;
            }
            set {
                this.codTipoCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numCuenta {
            get {
                return this.numCuentaField;
            }
            set {
                this.numCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nitEntidad {
            get {
                return this.nitEntidadField;
            }
            set {
                this.nitEntidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreEntidad {
            get {
                return this.nombreEntidadField;
            }
            set {
                this.nombreEntidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumTipoCuentaBancaria {
        
        /// <remarks/>
        AHR,
        
        /// <remarks/>
        CRR,
        
        /// <remarks/>
        DEL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoMedioPago {
        
        private enumTipoMedioPago codMedioPagoField;
        
        private string nomMedioPagoField;
        
        private tipoCuentaBancaria cuentaBancariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumTipoMedioPago codMedioPago {
            get {
                return this.codMedioPagoField;
            }
            set {
                this.codMedioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomMedioPago {
            get {
                return this.nomMedioPagoField;
            }
            set {
                this.nomMedioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tipoCuentaBancaria cuentaBancaria {
            get {
                return this.cuentaBancariaField;
            }
            set {
                this.cuentaBancariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumTipoMedioPago {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        TT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemObligacion {
        
        private string codPCIField;
        
        private string nomPCIField;
        
        private long codObligacionField;
        
        private System.DateTime fechaRegistroField;
        
        private System.DateTime fechaCreacionField;
        
        private string estadoField;
        
        private decimal valorInicialField;
        
        private decimal valorActualField;
        
        private decimal valorDeduccionesField;
        
        private decimal valorObligNoOrdenField;
        
        private tipoTerceroBasico terceroBeneficiarioField;
        
        private tipoMedioPago medioPagoField;
        
        private tipoItemAfectacion[] listaItemAfectacionField;
        
        private tipoDocRelacionObligacion docRelacionField;
        
        private tipoItemDeduccion[] listaItemDeduccionField;
        
        private tipoDatosAdminSimple datosAdminCompromisoField;
        
        private tipoDatosAdminSimple datosAdminObligacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCI {
            get {
                return this.codPCIField;
            }
            set {
                this.codPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPCI {
            get {
                return this.nomPCIField;
            }
            set {
                this.nomPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codObligacion {
            get {
                return this.codObligacionField;
            }
            set {
                this.codObligacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorInicial {
            get {
                return this.valorInicialField;
            }
            set {
                this.valorInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorActual {
            get {
                return this.valorActualField;
            }
            set {
                this.valorActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorDeducciones {
            get {
                return this.valorDeduccionesField;
            }
            set {
                this.valorDeduccionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorObligNoOrden {
            get {
                return this.valorObligNoOrdenField;
            }
            set {
                this.valorObligNoOrdenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoTerceroBasico terceroBeneficiario {
            get {
                return this.terceroBeneficiarioField;
            }
            set {
                this.terceroBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoMedioPago medioPago {
            get {
                return this.medioPagoField;
            }
            set {
                this.medioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemAfectacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemAfectacion[] listaItemAfectacion {
            get {
                return this.listaItemAfectacionField;
            }
            set {
                this.listaItemAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoDocRelacionObligacion docRelacion {
            get {
                return this.docRelacionField;
            }
            set {
                this.docRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemDeduccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemDeduccion[] listaItemDeduccion {
            get {
                return this.listaItemDeduccionField;
            }
            set {
                this.listaItemDeduccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoDatosAdminSimple datosAdminCompromiso {
            get {
                return this.datosAdminCompromisoField;
            }
            set {
                this.datosAdminCompromisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoDatosAdminSimple datosAdminObligacion {
            get {
                return this.datosAdminObligacionField;
            }
            set {
                this.datosAdminObligacionField = value;
            }
        }
    }
}
