//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 
namespace ComplementApp.API.Dtos.Serializacion.Compromiso {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    [System.Xml.Serialization.XmlRootAttribute("compromisoPptal", Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg", IsNullable=false)]
    public partial class tipoCompromisoPptal {
        
        private tipoListaFiltroConsulta listaFiltroConsultaField;
        
        private tipoItemCompromiso[] listaItemCompromisoField;
        
        private string numRegistroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoListaFiltroConsulta listaFiltroConsulta {
            get {
                return this.listaFiltroConsultaField;
            }
            set {
                this.listaFiltroConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemCompromiso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemCompromiso[] listaItemCompromiso {
            get {
                return this.listaItemCompromisoField;
            }
            set {
                this.listaItemCompromisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numRegistro {
            get {
                return this.numRegistroField;
            }
            set {
                this.numRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoListaFiltroConsulta {
        
        private string codPCIField;
        
        private string codPCIConsultaField;
        
        private string areaField;
        
        private enumCodTipoVigenciaTodas codTipoVigenciaField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private enumSINO continuidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCI {
            get {
                return this.codPCIField;
            }
            set {
                this.codPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCIConsulta {
            get {
                return this.codPCIConsultaField;
            }
            set {
                this.codPCIConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumCodTipoVigenciaTodas codTipoVigencia {
            get {
                return this.codTipoVigenciaField;
            }
            set {
                this.codTipoVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumSINO continuidad {
            get {
                return this.continuidadField;
            }
            set {
                this.continuidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumCodTipoVigenciaTodas {
        
        /// <remarks/>
        ACTUAL,
        
        /// <remarks/>
        RESERVAS_PRESUPUESTALES,
        
        /// <remarks/>
        CUENTAS_POR_PAGAR,
        
        /// <remarks/>
        TODAS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumSINO {
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        NO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoDatosAdminSimple {
        
        private System.DateTime fechaField;
        
        private string codTipoDocSoporteField;
        
        private string nomTipoDocSoporteField;
        
        private string numDocSoporteField;
        
        private string notasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoDocSoporte {
            get {
                return this.codTipoDocSoporteField;
            }
            set {
                this.codTipoDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTipoDocSoporte {
            get {
                return this.nomTipoDocSoporteField;
            }
            set {
                this.nomTipoDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocSoporte {
            get {
                return this.numDocSoporteField;
            }
            set {
                this.numDocSoporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemPlanPago {
        
        private string codDepAfectacioPACField;
        
        private string nomDepAfectacioPACField;
        
        private string codPosicionPACField;
        
        private string nomPosicionPACField;
        
        private System.DateTime fechaPagoField;
        
        private decimal valorField;
        
        private decimal saldoObligarField;
        
        private string codlineapagoField;
        
        private string nomlineapagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codDepAfectacioPAC {
            get {
                return this.codDepAfectacioPACField;
            }
            set {
                this.codDepAfectacioPACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomDepAfectacioPAC {
            get {
                return this.nomDepAfectacioPACField;
            }
            set {
                this.nomDepAfectacioPACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPosicionPAC {
            get {
                return this.codPosicionPACField;
            }
            set {
                this.codPosicionPACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPosicionPAC {
            get {
                return this.nomPosicionPACField;
            }
            set {
                this.nomPosicionPACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal saldoObligar {
            get {
                return this.saldoObligarField;
            }
            set {
                this.saldoObligarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codlineapago {
            get {
                return this.codlineapagoField;
            }
            set {
                this.codlineapagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomlineapago {
            get {
                return this.nomlineapagoField;
            }
            set {
                this.nomlineapagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemAfectacion {
        
        private string codDepAfectacionField;
        
        private string nomDepAfectacionField;
        
        private string codPosicionGastoField;
        
        private string nomPosicionGastoField;
        
        private string codFuenteFinanciacionField;
        
        private enumFuenteFinanciacion nomFuenteFinanciacionField;
        
        private string codRecursoPptalField;
        
        private string nomRecursoPptalField;
        
        private string codSituacionFondosField;
        
        private enumSituacionFondos nomSituacionFondosField;
        
        private decimal valorInicialField;
        
        private decimal valorOperacionesField;
        
        private decimal valorActualField;
        
        private decimal saldoUtilizarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codDepAfectacion {
            get {
                return this.codDepAfectacionField;
            }
            set {
                this.codDepAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomDepAfectacion {
            get {
                return this.nomDepAfectacionField;
            }
            set {
                this.nomDepAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPosicionGasto {
            get {
                return this.codPosicionGastoField;
            }
            set {
                this.codPosicionGastoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPosicionGasto {
            get {
                return this.nomPosicionGastoField;
            }
            set {
                this.nomPosicionGastoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codFuenteFinanciacion {
            get {
                return this.codFuenteFinanciacionField;
            }
            set {
                this.codFuenteFinanciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumFuenteFinanciacion nomFuenteFinanciacion {
            get {
                return this.nomFuenteFinanciacionField;
            }
            set {
                this.nomFuenteFinanciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codRecursoPptal {
            get {
                return this.codRecursoPptalField;
            }
            set {
                this.codRecursoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomRecursoPptal {
            get {
                return this.nomRecursoPptalField;
            }
            set {
                this.nomRecursoPptalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codSituacionFondos {
            get {
                return this.codSituacionFondosField;
            }
            set {
                this.codSituacionFondosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumSituacionFondos nomSituacionFondos {
            get {
                return this.nomSituacionFondosField;
            }
            set {
                this.nomSituacionFondosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorInicial {
            get {
                return this.valorInicialField;
            }
            set {
                this.valorInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorOperaciones {
            get {
                return this.valorOperacionesField;
            }
            set {
                this.valorOperacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorActual {
            get {
                return this.valorActualField;
            }
            set {
                this.valorActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal saldoUtilizar {
            get {
                return this.saldoUtilizarField;
            }
            set {
                this.saldoUtilizarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumFuenteFinanciacion {
        
        /// <remarks/>
        NACION,
        
        /// <remarks/>
        PROPIOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumSituacionFondos {
        
        /// <remarks/>
        CSF,
        
        /// <remarks/>
        SSF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoCajaMejor {
        
        private enumTipoMedioAdministrar codRegistroField;
        
        private string fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumTipoMedioAdministrar codRegistro {
            get {
                return this.codRegistroField;
            }
            set {
                this.codRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumTipoMedioAdministrar {
        
        /// <remarks/>
        CB,
        
        /// <remarks/>
        EF,
        
        /// <remarks/>
        CE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoOrdenadorGasto {
        
        private string codTipoDocumentoField;
        
        private string nomTipoDocumentoField;
        
        private string numDocIdentidadField;
        
        private string nomTerceroField;
        
        private string codCargoField;
        
        private string nomCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoDocumento {
            get {
                return this.codTipoDocumentoField;
            }
            set {
                this.codTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTipoDocumento {
            get {
                return this.nomTipoDocumentoField;
            }
            set {
                this.nomTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocIdentidad {
            get {
                return this.numDocIdentidadField;
            }
            set {
                this.numDocIdentidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTercero {
            get {
                return this.nomTerceroField;
            }
            set {
                this.nomTerceroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codCargo {
            get {
                return this.codCargoField;
            }
            set {
                this.codCargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomCargo {
            get {
                return this.nomCargoField;
            }
            set {
                this.nomCargoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoCuentaBancaria {
        
        private System.Nullable<enumTipoCuentaBancaria> codTipoCuentaField;
        
        private string numCuentaField;
        
        private string estadoField;
        
        private string nitEntidadField;
        
        private string nombreEntidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<enumTipoCuentaBancaria> codTipoCuenta {
            get {
                return this.codTipoCuentaField;
            }
            set {
                this.codTipoCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numCuenta {
            get {
                return this.numCuentaField;
            }
            set {
                this.numCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nitEntidad {
            get {
                return this.nitEntidadField;
            }
            set {
                this.nitEntidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreEntidad {
            get {
                return this.nombreEntidadField;
            }
            set {
                this.nombreEntidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumTipoCuentaBancaria {
        
        /// <remarks/>
        AHR,
        
        /// <remarks/>
        CRR,
        
        /// <remarks/>
        DEL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoMedioPago {
        
        private enumTipoMedioPago codMedioPagoField;
        
        private string nomMedioPagoField;
        
        private tipoCuentaBancaria cuentaBancariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumTipoMedioPago codMedioPago {
            get {
                return this.codMedioPagoField;
            }
            set {
                this.codMedioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomMedioPago {
            get {
                return this.nomMedioPagoField;
            }
            set {
                this.nomMedioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tipoCuentaBancaria cuentaBancaria {
            get {
                return this.cuentaBancariaField;
            }
            set {
                this.cuentaBancariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumTipoMedioPago {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        TT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoTerceroBasico {
        
        private string nomTerceroField;
        
        private string codNaturalezaField;
        
        private string nomNaturalezaField;
        
        private string codTipoDocumentoField;
        
        private string nomTipoDocumentoField;
        
        private string numDocIdentidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTercero {
            get {
                return this.nomTerceroField;
            }
            set {
                this.nomTerceroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codNaturaleza {
            get {
                return this.codNaturalezaField;
            }
            set {
                this.codNaturalezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomNaturaleza {
            get {
                return this.nomNaturalezaField;
            }
            set {
                this.nomNaturalezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoDocumento {
            get {
                return this.codTipoDocumentoField;
            }
            set {
                this.codTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomTipoDocumento {
            get {
                return this.nomTipoDocumentoField;
            }
            set {
                this.nomTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocIdentidad {
            get {
                return this.numDocIdentidadField;
            }
            set {
                this.numDocIdentidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public partial class tipoItemCompromiso {
        
        private string codPCIField;
        
        private string nomPCIField;
        
        private long codCompromisoField;
        
        private string estadoField;
        
        private System.DateTime fechaRegistroField;
        
        private long codCDPField;
        
        private System.DateTime fechaCDPField;
        
        private string codMonedaField;
        
        private string nomMonedaField;
        
        private System.Nullable<decimal> valorTasaField;
        
        private enumCodTipoVigencia codTipoVigenciaField;
        
        private decimal valorInicialField;
        
        private System.Nullable<decimal> valorInicialMonedaField;
        
        private decimal valorOperacionesField;
        
        private decimal valorActualField;
        
        private decimal saldoObligarField;
        
        private System.Nullable<decimal> saldoMonedaField;
        
        private string objetoField;
        
        private tipoTerceroBasico terceroBeneficiarioField;
        
        private tipoMedioPago medioPagoField;
        
        private tipoOrdenadorGasto ordenadorGastoField;
        
        private tipoCajaMejor cajaMenorField;
        
        private tipoItemAfectacion[] listaItemAfectacionField;
        
        private tipoItemPlanPago[] listaItemPlanPagoField;
        
        private tipoDatosAdminSimple datosAdminField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPCI {
            get {
                return this.codPCIField;
            }
            set {
                this.codPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomPCI {
            get {
                return this.nomPCIField;
            }
            set {
                this.nomPCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codCompromiso {
            get {
                return this.codCompromisoField;
            }
            set {
                this.codCompromisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codCDP {
            get {
                return this.codCDPField;
            }
            set {
                this.codCDPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaCDP {
            get {
                return this.fechaCDPField;
            }
            set {
                this.fechaCDPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomMoneda {
            get {
                return this.nomMonedaField;
            }
            set {
                this.nomMonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> valorTasa {
            get {
                return this.valorTasaField;
            }
            set {
                this.valorTasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enumCodTipoVigencia codTipoVigencia {
            get {
                return this.codTipoVigenciaField;
            }
            set {
                this.codTipoVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorInicial {
            get {
                return this.valorInicialField;
            }
            set {
                this.valorInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> valorInicialMoneda {
            get {
                return this.valorInicialMonedaField;
            }
            set {
                this.valorInicialMonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorOperaciones {
            get {
                return this.valorOperacionesField;
            }
            set {
                this.valorOperacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorActual {
            get {
                return this.valorActualField;
            }
            set {
                this.valorActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal saldoObligar {
            get {
                return this.saldoObligarField;
            }
            set {
                this.saldoObligarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> saldoMoneda {
            get {
                return this.saldoMonedaField;
            }
            set {
                this.saldoMonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoTerceroBasico terceroBeneficiario {
            get {
                return this.terceroBeneficiarioField;
            }
            set {
                this.terceroBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoMedioPago medioPago {
            get {
                return this.medioPagoField;
            }
            set {
                this.medioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoOrdenadorGasto ordenadorGasto {
            get {
                return this.ordenadorGastoField;
            }
            set {
                this.ordenadorGastoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tipoCajaMejor cajaMenor {
            get {
                return this.cajaMenorField;
            }
            set {
                this.cajaMenorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemAfectacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemAfectacion[] listaItemAfectacion {
            get {
                return this.listaItemAfectacionField;
            }
            set {
                this.listaItemAfectacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemPlanPago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tipoItemPlanPago[] listaItemPlanPago {
            get {
                return this.listaItemPlanPagoField;
            }
            set {
                this.listaItemPlanPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoDatosAdminSimple datosAdmin {
            get {
                return this.datosAdminField;
            }
            set {
                this.datosAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.minhacienda.gov.co/mhcp/siifnacion/transferenciaxml/epg")]
    public enum enumCodTipoVigencia {
        
        /// <remarks/>
        ACTUAL,
        
        /// <remarks/>
        RESERVAS_PRESUPUESTALES,
        
        /// <remarks/>
        CUENTAS_POR_PAGAR,
    }
}
